#!/usr/bin/env perl
# Copyright © 2008-2012 Kevin Spencer <kevin@kevinspencer.org>
#
# Permission to use, copy, modify, distribute, and sell this software and its
# documentation for any purpose is hereby granted without fee, provided that
# the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation.  No representations are made about the suitability of this
# software for any purpose.  It is provided "as is" without express or 
# implied warranty.
#
################################################################################

use Getopt::Std;
use HTML::Entities;
use strict;
use warnings;

getopts('c:');
our $opt_c;

our $VERSION = '0.25';

if (($opt_c) && ($opt_c =~ /\D/)) {
    die "Count specified with -c must be numeric\n";
}

my $user = getpwuid($<);
my $libraryPath = "/Users/$user/Music/iTunes/iTunes Music Library.xml";
open(my $lfh, '<', $libraryPath) || die "Could not open $libraryPath - $!\n";

my %count;
# regex XML parsing for the win...
while (<$lfh>) {
    my $line = $_;
    if ($line =~ /<key>Artist<\/key><string>(.+)<\/string>/) {
        my $artist = $1;
        $count{$artist}++;
    }
}
close($lfh);
if (%count) {
    my $counter = 0;
    for my $artist (reverse(sort { $count{$a} <=> $count{$b} } keys(%count))) {
        my $decoded_artist = decode_entities($artist);
        printf "%4d %s\n", $count{$artist}, $decoded_artist;
        $counter++;
        last if (($opt_c) && ($opt_c == $counter));
    }
}

